<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'lrn',
        'name',
        'birthday',
        'age',
        'gender',
        'place_of_birth',
        'home_address',
        'contact_number',
        'name_father',
        'birthday_father',
        'occupation_father',
        'home_address_father',
        'contact_number_father',
        'name_mother',
        'birthday_mother',
        'occupation_mother',
        'home_address_mother',
        'contact_number_mother',
        'name_guardian',
        'birthday_guardian',
        'occupation_guardian',
        'home_address_guardian',
        'contact_number_guardian',
        'name_sibling',
        'age_sibling',
        'school_attended_kindergarten',
        'year_completed_kindergarten',
        'academic_standing_kindergarten',
        'school_attended_grade1',
        'year_completed_grade1',
        'academic_standing_grade1',
        'school_attended_grade2',
        'year_completed_grade2',
        'academic_standing_grade2',
        'school_attended_grade3',
        'year_completed_grade3',
        'academic_standing_grade3',
        'school_attended_grade4',
        'year_completed_grade4',
        'academic_standing_grade4',
        'school_attended_grade5',
        'year_completed_grade5',
        'academic_standing_grade5',
        'school_attended_grade6',
        'year_completed_grade6',
        'academic_standing_grade6',
        'school_attended_grade7',
        'year_completed_grade7',
        'academic_standing_grade7',
        'school_attended_grade8',
        'year_completed_grade8',
        'academic_standing_grade8',
        'school_attended_grade9',
        'year_completed_grade9',
        'academic_standing_grade9',
        'school_attended_grade10',
        'year_completed_grade10',
        'academic_standing_grade10',
        'school_attended_grade11',
        'year_completed_grade11',
        'academic_standing_grade11',
        'school_attended_grade12',
        'year_completed_grade12',
        'academic_standing_grade12'
    ];
}
